### ISSUE TITLE
Add support for Pelitorrent site

### ISSUE THREAD

**Issue by patamimbre** [kekazoh/peerflix-scraper#15]
https://www.pelitorrent.com/

**Comment by kekazoh** [comment]
Working on this one on https://github.com/kekazoh/peerflix-scraper/tree/feature/pelitorrent-scraper

**Comment by gecm0** [comment]
> Working on this one on https://github.com/kekazoh/peerflix-scraper/tree/feature/pelitorrent-scraper

Oh, I started working on this yesterday at midnight 😅 Leaving this to you 👍🏻

**Comment by gecm0** [comment]
We have to find a good way to sync against tasks haha
My changes are available on `patamimbre/pelitorrent` if you want to pick them

**Comment by kekazoh** [comment]
Oh sorry about that! I didn't see your branch. Maybe we could standardize the branch naming convention to `feature/title-of-the-issue-in-snake-case` and publish it as soon as we start working on it. So we can easily trace it back to the issue and avoid working on the same things.
Here is the pull request in case you want to check it out: https://github.com/kekazoh/peerflix-scraper/pull/17
