### ISSUE TITLE
Add support for "Cajón de Torrents 202409"

### ISSUE THREAD

**Issue by patamimbre** [kekazoh/peerflix-scraper#16]
https://t.me/addlist/LEkpagDTaQ9hMzM0

**Comment by kekazoh** [comment]
Solved already on [051fda1d2a9ad2a8c8db54f7c7926d41084e10dd](https://github.com/kekazoh/peerflix-scraper/tree/051fda1d2a9ad2a8c8db54f7c7926d41084e10dd)

**Comment by XDeadHackerX** [comment]
> Solved already on [051fda1d2a9ad2a8c8db54f7c7926d41084e10dd](https://github.com/kekazoh/peerflix-scraper/tree/051fda1d2a9ad2a8c8db54f7c7926d41084e10dd)

Muchas gracias @kekazoh , puedes añadirlo a la rama principal para que podamos usarlo¿?
